// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(FinalProjectContext))]
    [Migration("20240507201859_NewInit2")]
    partial class NewInit2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrivateMoveId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrivateMoveId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FinalProject.Models.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ElevatorFromAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("ElevatorToAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("FurnitureLiftFromAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("FurnitureLiftToAddress")
                        .HasColumnType("bit");

                    b.Property<int>("PrivateMoveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrivateMoveId")
                        .IsUnique();

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("FinalProject.Models.PrivateMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Packing")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PackingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PackingPaper")
                        .HasColumnType("bit");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnloadingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Unpacking")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UnpackingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PrivateMoves");
                });

            modelBuilder.Entity("FinalProject.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Hot")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Not")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("FinalProject.Models.Address", b =>
                {
                    b.HasOne("FinalProject.Models.PrivateMove", "PrivateMove")
                        .WithMany("Addresses")
                        .HasForeignKey("PrivateMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateMove");
                });

            modelBuilder.Entity("FinalProject.Models.Amenities", b =>
                {
                    b.HasOne("FinalProject.Models.PrivateMove", "PrivateMove")
                        .WithOne("Amenities")
                        .HasForeignKey("FinalProject.Models.Amenities", "PrivateMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateMove");
                });

            modelBuilder.Entity("FinalProject.Models.PrivateMove", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Amenities")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
